import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className="bg-[#121429]">
        <body className="bg-[#121429]">
            <header className="flex justify-between bg-[#121429] text-white">
                <div><p>LOGO</p></div>
                <nav className="space-x-5">
                    <a href="#about">ABOUT</a>
                    <a href="#project">PROJEKTE</a>
                    <a href="#process">PROZESS</a>
                    <a className="mr-5" href="#contact">KONTAKT</a>
                </nav>
            </header>
            <main className="bg-[#121429] text-white">
                {children}
            </main>
        </body>
        </html>
    );
}
