import {Outfit, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className={`bg-[#121429] ${outfit.variable} ${geistMono.variable}`}>
        <body className={`bg-[#121429] ${outfit.variable} ${geistMono.variable}`}>
        <Header></Header>
        <main className="bg-[#121429] text-white">
            {children}
        </main>
        <Footer></Footer>
        </body>
        </html>
    );
}
